CREATE DATABASE IF NOT EXISTS montenegro CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE montenegro;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','avaliador') NOT NULL DEFAULT 'avaliador',
  avatar_url TEXT NULL,
  bio VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS works (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  kind ENUM('livro','filme','serie') NOT NULL,
  creator VARCHAR(180) NOT NULL,
  publisher VARCHAR(180) NULL,
  release_date DATE NULL,
  year SMALLINT UNSIGNED NULL,
  genre VARCHAR(100) NULL,
  synopsis TEXT NULL,
  image_url TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_works_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_works_kind (kind),
  INDEX idx_works_title (title)
);

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  work_id BIGINT UNSIGNED NOT NULL,
  mode ENUM('rapida','detalhada') NOT NULL DEFAULT 'rapida',
  rating TINYINT UNSIGNED NOT NULL,
  worth_it ENUM('sim','mais_ou_menos','nao') NOT NULL,
  comment TEXT NULL,
  emotion VARCHAR(160) NULL,
  verdict VARCHAR(180) NULL,
  scores JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_reviews_work FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE,
  CONSTRAINT uq_review_user_work UNIQUE (user_id, work_id),
  CONSTRAINT chk_rating CHECK (rating BETWEEN 1 AND 5),
  INDEX idx_reviews_work (work_id),
  INDEX idx_reviews_user (user_id)
);

CREATE TABLE IF NOT EXISTS shelves (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_shelves_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT uq_shelf_name UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS shelf_items (
  shelf_id BIGINT UNSIGNED NOT NULL,
  work_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (shelf_id, work_id),
  CONSTRAINT fk_shelf_items_shelf FOREIGN KEY (shelf_id) REFERENCES shelves(id) ON DELETE CASCADE,
  CONSTRAINT fk_shelf_items_work FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE
);
